### ISSUE TITLE
Dynamic sheet doesn't update because of this plugin

### ISSUE THREAD

**Issue by mistadikay** [iamstarkov/jss-increase-id-specificity#3]
Hey!

I'm using `react-jss` with rules like:
```js
borderColor: ({ isValid }) => (isValid ? '#a5a5a5' : '#f00')
```

When `isValid` prop changes I can see that this function executes and returned value is correct, but the sheet doesn't update and visually border-color stays the same.

While debugging this issue I found out that this plugin was the problem, in particular [this string](https://github.com/iamstarkov/jss-increase-id-specificity/blob/master/index.js#L18) in `onProcessSheet` hook:
```js
rule.selectorText = prefix + rule.selectorText;
```

My questions are more to @kof I guess:
1) what is the correct way to change selector (assuming that the one described above is incorrect) to make dynamic sheets work?
2) could it be maybe connected with [this issue](https://github.com/cssinjs/react-jss/issues/94)?

Any help appreciated, thanks.

**Comment by kof** [comment]
Not sure how this can be related to the selector. What JSS version are you using? (See in node_modules/jss, not in your package.json)

**Comment by mistadikay** [comment]
It's `7.1.7`. I can try to isolate this issue to some repo or something if that would be helpful?

**Comment by kof** [comment]
yes please, for e.g. on webpackbin

**Comment by kof** [comment]
so when you exclude that plugin, it works, right? if so we just need to debug, no need for example.

**Comment by mistadikay** [comment]
yep, that's correct

**Comment by mistadikay** [comment]
here you go: https://www.webpackbin.com/bins/-KmwwbmmD04uCB2nPKDt Since the latest version of the plugin is not published, I just inlined it in `jss.js`

**Comment by mistadikay** [comment]
Did you have time to look into this issue @kof? Can I help?

**Comment by iamstarkov** [comment]
close in favor of another one https://github.com/iamstarkov/jss-increase-specificity/issues/2
